#!/usr/bin/env bash
#Copyright (C) 2015  Helal Uddin <helal00 at gmail.com>
#This program is free software: you can redistribute it and/or modify
#it under the terms of the GNU General Public License as published by
#the Free Software Foundation, either version 3 of the License, or
#(at your option) any later version.
#
#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.
#
#You should have received a copy of the GNU General Public License
#along with this program.  If not, see <http://www.gnu.org/licenses/>.

_srcsbinpath=$(dirname $(readlink -f $0))

declare -a _requiredfiles
declare -a _requiredexefiles

_requiredfiles[${#_requiredfiles[@]}]="functions"

if [ ! -z "$_srcsbinpath" ] ; then
	if [ -s "$_srcsbinpath/resolve" ] ; then
		. $_srcsbinpath/resolve	
	else
		echo "$_srcsbinpath/resolve file not found!" 1>&2
		exit 1
	fi
fi

if [ ! -d "$_srcsbinpath/.store" ] ; then
	echo "The prgram is not yet ready to run. Please run $_srcsbinpath/installme first." 1>&2
	exit 1
fi
_delete=""
_counter=0
_curcounter=0
_ip=$1


if [ -z "$_ip" ] ; then
	echo "No ip given." 1>&2
	exit 1
else
	if [ -f "$_srcsbinpath/balcklist.db" ] ; then
		_ipline=$(grep "$_ip" "$_srcsbinpath/balcklist.db")
		if [ -z "$_ipline" ] ; then
			echo "No Such ip : $_ip found in database."
			exit 1
		fi
		read -p "Are you sure, you want disable/delete ip :  $_ip. (yes/enter onlyto cancel): " _besure
		_besure=${_besure,,}
		if [ -z "$_besure" ] || [ "$_besure" != "yes" ] ; then
			exit 0
		fi
	else
		echo "No database found."
		exit 1
	fi
fi

if [ "$2" = "del" ] ; then
_delete="del"
fi


if [ "$2" = "set" ] && isint $3 ; then
	_curcounter=$(echo $_ipline | awk -F"|" '{print $2}')
	if [ "$3" -ge 0 ] ; then
		_counter=$3
	else
		_counter=$[_curcounter+$3]
	fi
	
	if [ "$_counter" -lt 1 ] ; then
		_counter=1
	fi
fi
_prefix=""
_doprefix="#"
if [ "${_ipline:0:1}" = "#" ] ; then
	_prefix="#"
	_doprefix=""
fi

if [ -z "$_delete" ] ; then
	if [ "$_counter" -gt 0 ] ; then
	sed -i "s/^$_prefix$_ip|$_curcounter/$_prefix$_doprefix$_ip|$_counter/" "$_srcsbinpath/balcklist.db"
	else
	sed -i "s/^$_prefix$_ip/$_prefix$_doprefix$_ip/" "$_srcsbinpath/balcklist.db"
	fi
else
	sed -i "/^$_prefix$_ip/d" "$_srcsbinpath/balcklist.db"
fi

for _ln in $(ufw status numbered |(grep "$_ip"|awk -F"[][]" '{print $2}'))
do
ufw --force delete $_ln
done
